import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from "../components/CustomCursor";
import { Header, Footer } from "../components";
import { LocaleProvider } from "../contexts/LocaleContext";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <body
        className={`antialiased min-h-screen flex flex-col`}
        suppressHydrationWarning>
        <LocaleProvider>
          <CustomCursor />
          <div className="fixed top-0 left-0 right-0 z-50 header-blur">
            <Header />
          </div>
          <main className="pt-14 flex-grow overflow-x-hidden">{children}</main>
          <Footer />
        </LocaleProvider>
      </body>
    </html>
  );
}
